### PR TITLE
Introduce Travis CI into project pipeline: pytest and codecov

### PR DESCRIPTION
**Pull request by abhabongse**
Notice how CI/CD runs here.  
_Please ignore AppVeyor errors as it is improperly configured. It has been removed but the cache still persists._

### CODE REVIEW

**Comment by sathachao** [comment]
- It seems that type checking is not fully supported in code coverage.
- Should we include codecov tag in README.md?

**Review by sathachao — APPROVED** [review]
LGTM. Will have to include codecov configuration file for customized passing criteria (probably required until most tests are written.)

**Comment by abhabongse** [comment]
> It seems that type checking is not fully supported in code coverage.

What do you mean specifically?

> * Should we include codecov badge in README.md?

> LGTM. Will have to include codecov configuration file for customized passing criteria (probably required until most tests are written.)

Yes, will do next.

**Comment by sathachao** [comment]
> > It seems that type checking is not fully supported in code coverage.
> 
> What do you mean specifically?
> 
For example, this specific part is not checked and seemingly affects code coverage
https://github.com/abhabongse/bluejayson/blob/2177e14fd67b6668c055f738ec419cd81ee9894f/bluejayson/fields.py#L3-L7

**Pull request merged**
